### ISSUE TITLE
controller gyro is very sensitive to forward/back movements, much more so than side to side or tilting

### ISSUE THREAD

**Issue by sage-of-flowers** [EX-XDRiVER/Issues#2]
for whatever reason, rolling controller forward/back has a much higher effect than a more expected movement, which can make drifting *really* weird when trying to work around keeping the controller even to prevent it from making motions weird

**Comment by tari-cat** [comment]
Possibly fixable by changing Controller Layout -> Gyro Behavior -> Gyro Turning Axis
