### ISSUE TITLE
No direction upon attempting to make two profiles with the same name

### ISSUE THREAD

**Issue by bippy20** [EX-XDRiVER/Issues#3]
I figure that you're not allowed to make two profiles with the same name given it's an online game, but if you try to the game doesn't give any feedback at all upon pressing enter on the name selection screen, so I thought my game froze for a moment LOL. (dont ask why i tried making two profiles with the same name im an idiot)

**Comment by tari-cat** [comment]
Probably causes an error, will look into it

**Comment by tari-cat** [comment]
Fixed in Beta 1.0.0.2
