### ISSUE TITLE
Switching between Linux and Proton/Windows builds wipes my saves.

### ISSUE THREAD

**Issue by rehtlaw** [EX-XDRiVER/Issues#4]
Seems like when switching between the Windows and Linux versions by forcing the use of Proton, it wipes my save files. Manually copying them over from AppData/LocalLow/EX-XDRiVER in the compatdata folder into ~/.local/share/EX-XDRiVER didn't seem to do anything (apparently nothing was actually saved there in the first place, even though it still saved my progress???).

**Comment by tari-cat** [comment]
If you can find the locations of the save files on Proton, I can investigate the Steam Cloud file paths
Currently on Linux + SteamOS they should be going to `$XDG_DATA_HOME/EX-XDRiVER/XDRV/Data/Profiles`

**Comment by tari-cat** [comment]
This issue needs confirmation, we've modified the file path to `~/.config/unity3d/EX-XDRiVER/XDRV/Data/Profiles` (in `$HOME`)

**Comment by rehtlaw** [comment]
> If you can find the locations of the save files on Proton, I can investigate the Steam Cloud file paths Currently on Linux + SteamOS they should be going to `$XDG_DATA_HOME/EX-XDRiVER/XDRV/Data/Profiles`

`compatdata/2636020/pfx/drive_c/users/steamuser/AppData/LocalLow/EX-XDRiVER/XDRV/` is the only thing I could find that remotely looks like it had my save files while using the Windows build with Proton, which is also where I would've expected it to put save data on Windows (even if they don't seem to have saved anything... at least the log files look correct tho).

I can confirm that for the native Linux version has its save data in `~/.config/unity3d/EX-XDRiVER/XDRV/`, although the `~/.local/share/EX-XDRiVER` folder also already existed.

**Comment by tari-cat** [comment]
Hey, I've found a way to add the cloud path for Proton builds, but I have no way of testing it. If you're still interested, could you test and see if it's good to go? Thanks!

**Comment by rehtlaw** [comment]
Yes I'm definitely interested in testing it out.

**Comment by tari-cat** [comment]
Re-opening this issue temporarily. Found the cross-platform saves issue. Could be worth backing up your saves via Steam remote storage before swapping platforms again. This should be good to go for all platforms now.
