### ISSUE TITLE
Game Volume problem

### ISSUE THREAD

**Issue by Marsoff9898** [EX-XDRiVER/Issues#7]
Hey folks.

I really like this game.

But I really like to report an issue with the game sound volume, cause it's either too quiet for the menus and too loud for the actual game charts.

**Comment by tari-cat** [comment]
Hey! If you go to Options, there are a few options available to change individual volume settings. Thanks!

![image](https://github.com/EX-XDRiVER/Issues/assets/76984137/4cdbfe52-5d52-418e-92c9-28432cac0417)

**Comment by Marsoff9898** [comment]
Nice. Now I have everything in normal 25% volume.Keep up the good work.
-------- Mensaje original --------De: tari ***@***.***> Fecha: 17/5/24  19:05  (GMT-03:00) A: EX-XDRiVER/Issues ***@***.***> CC: Marsoff9898 ***@***.***>, Author ***@***.***> Asunto: Re: [EX-XDRiVER/Issues] Game Volume problem (Issue #7) 
Hey! If you go to Options, there are a few options available to change individual volume settings. Thanks!
image.png (view on web)
