### ISSUE TITLE
Mistyped info

### ISSUE THREAD

**Issue by bruhh24** [EX-XDRiVER/Issues#8]
In options/volume menu there is a wrong description for song preview volume.
![image_2024-10-13_110311939](https://github.com/user-attachments/assets/f884ff68-650f-471b-99fc-52f63cd1ff14)

**Comment by tari-cat** [comment]
Whoops! Good catch.
I'll get this fixed for the next update. Thank you!

**Comment by tari-cat** [comment]
Fixed as of 1.4.0 (next update)
